supi: "imsi-001010000000002"
mcc: "001"
mnc: "01"
key: "465B5CE8B199B49FAA5F0A2EE238A6B0"
opType: "OPC"
op: "E8ED289DEBA952E4283B54E88E6183B8"
amf: "8000"

# Procura o gNB pelo IP do serviço ueransim-gnb (na rede docker)
gnbSearchList:
  - 10.20.0.101

# Sessão / PDU
sessions:
  - type: "IPv4"
    apn: "internet"        # DNN configurado no SMF/UPF (open5gs)
    slice:
      sst: 1

integrity:
  IA1: false
  IA2: true
  IA3: false

integrityMaxRate:
  uplink: full
  downlink: full

ciphering:
  EA1: false
  EA2: false
  EA3: false
  EA0: true

uacAic:
  mps: false
  mcs: false

uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false
