#!/usr/bin/env bash
set -euo pipefail

# Dump/restores the local MongoDB database used by Open5GS on the host.
#
# This script is meant to be used before destructive DB operations (like dropping collections).
# The dump is compatible with restore generated by this same tool.
#
# Usage:
#   ./dump-restore-open5gs-db.sh dump [--out <base_dir>]
#   ./dump-restore-open5gs-db.sh restore <backup_dir>
#
# Default backup location (sem --out): <open5gs-x310>/db-backups/open5gs-<timestamp>/
#
# Examples (a partir do repo):
#   BACKUP_DIR="$(./code/open5gs-x310/scripts/dump-restore-open5gs-db.sh dump)"
#   ./code/open5gs-x310/scripts/dump-restore-open5gs-db.sh restore "$BACKUP_DIR"

DB_NAME="open5gs"
MONGO_URI="${MONGO_URI:-mongodb://127.0.0.1:27017}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# Para stop/start durante restore:
# shellcheck source=open5gs-systemd.inc.sh
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/open5gs-systemd.inc.sh"
# Backups ficam fora de scripts/: <open5gs-x310>/db-backups/
DEFAULT_BACKUP_BASE="${DEFAULT_BACKUP_BASE:-${PROJECT_ROOT}/db-backups}"

usage() {
  cat <<EOF
Usage:
  dump:    ./dump-restore-open5gs-db.sh dump [--out <base_dir>]
  restore: ./dump-restore-open5gs-db.sh restore <backup_dir>

Sem --out, o dump vai para:
  ${PROJECT_ROOT}/db-backups/open5gs-<timestamp>/
EOF
}

cmd="${1:-}"
if [[ -z "${cmd}" ]]; then
  usage
  exit 1
fi

case "${cmd}" in
  dump)
    OUT_BASE="${DEFAULT_BACKUP_BASE}"

    # very small option parser for --out <dir>
    shift || true
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --out)
          OUT_BASE="${2:?--out requires a value}"
          shift 2
          ;;
        --out=*)
          OUT_BASE="${1#*=}"
          shift 1
          ;;
        -h|--help)
          usage
          exit 0
          ;;
        *)
          echo "Unknown argument: $1" >&2
          usage
          exit 1
          ;;
      esac
    done

    mkdir -p "${OUT_BASE}"

    TS="$(date '+%Y%m%d-%H%M%S')"
    BACKUP_DIR="${OUT_BASE}/open5gs-${TS}"

    echo "==> MongoDB dump ($DB_NAME) para: ${BACKUP_DIR}" >&2
    mongodump --uri "${MONGO_URI}" --db "${DB_NAME}" --out "${BACKUP_DIR}" >/dev/null

    echo "${BACKUP_DIR}"
    ;;

  restore)
    BACKUP_DIR="${2:-}"
    if [[ -z "${BACKUP_DIR}" ]]; then
      echo "Missing <backup_dir>" >&2
      usage
      exit 1
    fi
    if [[ ! -d "${BACKUP_DIR}" ]]; then
      echo "Backup dir not found: ${BACKUP_DIR}" >&2
      exit 1
    fi

    # mongodump created: <backup_dir>/open5gs/<collection>/*.bson
    SRC_DIR="${BACKUP_DIR}/open5gs"
    if [[ ! -d "${SRC_DIR}" ]]; then
      # allow passing directly the inner open5gs directory
      SRC_DIR="${BACKUP_DIR}"
    fi

    echo "==> Restaurando MongoDB ($DB_NAME) a partir de: ${SRC_DIR}" >&2

    if open5gs_any_running; then
      open5gs_stop_stack
    fi

    mongorestore --uri "${MONGO_URI}" --drop -d "${DB_NAME}" "${SRC_DIR}" >/dev/null

    open5gs_start_stack

    echo "==> Restore concluído." >&2
    ;;

  *)
    echo "Unknown command: ${cmd}" >&2
    usage
    exit 1
    ;;
esac

